# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.snowman.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'snowman', 'function_path': 'animated_java:snowman/animations/idle_wave/next_frame'}
execute if score @s aj.idle_wave.frame matches 40.. run scoreboard players set @s aj.idle_wave.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.idle_wave.frame
execute at @s run function animated_java:snowman/animations/idle_wave/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.idle_wave.frame 1