# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.snowman.root] run return 0
execute on passengers if entity @s[tag=aj.snowman.data] unless data entity @s {data:{rigHash: '51919480e863a3381151c28f4ad14433cf68164c0419e590928611e411e0a86d'}} on vehicle run function animated_java:snowman/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1