# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.snowman.root] run return 0
execute on passengers if entity @s[tag=aj.snowman.data] unless data entity @s {data:{rigHash: 'c1087240792bc704ee77de6e0f77b545aacc2758e7fffe82f2c6fe028b921a8a'}} on vehicle run function animated_java:snowman/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1