# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.snowman.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:snowman/as_root/pre_tick
execute if entity @s[tag=aj.snowman.animation.idle_lookaround.playing] run function animated_java:snowman/animations/idle_lookaround/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.idle_wave.playing] run function animated_java:snowman/animations/idle_wave/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.idle_sway.playing] run function animated_java:snowman/animations/idle_sway/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.target_player.playing] run function animated_java:snowman/animations/target_player/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.untarget_player.playing] run function animated_java:snowman/animations/untarget_player/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.prepare_shot.playing] run function animated_java:snowman/animations/prepare_shot/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.shoot.playing] run function animated_java:snowman/animations/shoot/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.spawn.playing] run function animated_java:snowman/animations/spawn/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.damage.playing] run function animated_java:snowman/animations/damage/zzz/on_tick
execute if entity @s[tag=aj.snowman.animation.death.playing] run function animated_java:snowman/animations/death/zzz/on_tick
execute on passengers if entity @s[tag=aj.snowman.data] run function animated_java:snowman/root/zzz/1
execute at @s on passengers run rotate @s ~ ~
function #animated_java:snowman/as_root/post_tick