# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.carrot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_carrot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.face] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_face set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.hat] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.buttons] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_buttons set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.scarf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_scarf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.bottom] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.snowball] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_snowball set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.leftarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftarm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.snowman.bone.rightarm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightarm set from storage aj:uuid main.out