# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.snowman.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'snowman', 'function_path': 'animated_java:snowman/variants/default/apply'}
execute on passengers if entity @s[tag=aj.snowman.bone.carrot] run function animated_java:snowman/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.snowman.bone.face] run function animated_java:snowman/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.snowman.bone.hat] run function animated_java:snowman/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.snowman.bone.head] run function animated_java:snowman/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.snowman.bone.buttons] run function animated_java:snowman/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.snowman.bone.scarf] run function animated_java:snowman/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.snowman.bone.body] run function animated_java:snowman/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.snowman.bone.bottom] run function animated_java:snowman/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.snowman.bone.snowball] run function animated_java:snowman/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.snowman.bone.snowball2] run function animated_java:snowman/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.snowman.bone.leftarm] run function animated_java:snowman/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.snowman.bone.rightarm] run function animated_java:snowman/variants/default/zzz/11