# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle_lookaround.frame dummy
scoreboard objectives add aj.idle_wave.frame dummy
scoreboard objectives add aj.idle_sway.frame dummy
scoreboard objectives add aj.target_player.frame dummy
scoreboard objectives add aj.untarget_player.frame dummy
scoreboard objectives add aj.prepare_shot.frame dummy
scoreboard objectives add aj.shoot.frame dummy
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.damage.frame dummy
scoreboard objectives add aj.death.frame dummy
execute as @e[type=item_display,tag=aj.snowman.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:snowman/root/on_load